# Generated by Django 4.0.2 on 2022-04-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=15, max_digits=19)),
                ('lon', models.DecimalField(decimal_places=15, max_digits=19)),
                ('radius', models.FloatField(default=0)),
            ],
        ),
    ]
