# Generated by Django 4.0.2 on 2022-07-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='tax',
            field=models.IntegerField(default=0),
        ),
    ]
